inherit_from:
  - .rubocop.ruby.yml
  - .rubocop.rspec.yml

plugins:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.3
  NewCops: disable
  SuggestExtensions: false
Naming/FileName:
  Exclude:
    - "Gemfile"
    - "Rakefile"
    - "bin/*"
Style/Documentation:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 5
RSpec/MultipleMemoizedHelpers:
  Max: 6
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/DescribedClass:
  EnforcedStyle: described_class  
